/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaPoliticaMod.java
 *
 * Created on 26/09/2011, 17:51:38
 */
package view;

import classe.Documento;
import classe.SingletonUtil;
import classe.Usuario;
import controle.DocumentoControle;
import controle.PoliticaModControle;
import controle.UsuarioControle;
import javax.swing.JOptionPane;

/**
 *
 * @author Priscilla
 */
public class TelaPoliticaMod extends javax.swing.JFrame {
    static Object txtidDoc;
    
    /** Creates new form TelaPoliticaMod */
    public TelaPoliticaMod() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbTpMod = new javax.swing.JComboBox();
        txtQtd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Política de Modularização");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        cmbTpMod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sob demanda", "Automática" }));
        cmbTpMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTpModActionPerformed(evt);
            }
        });
        cmbTpMod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbTpModFocusLost(evt);
            }
        });

        jLabel1.setText("Tipo de Modularização");

        jLabel2.setText("Quantidade de Palavras");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(27, 27, 27)
                                .addComponent(cmbTpMod, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbTpMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 324, 134);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-340)/2, (screenSize.height-174)/2, 340, 174);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        TelaAnotacao a = new TelaAnotacao();
        this.dispose();
        a.setVisible(true);
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        PoliticaModControle pol = new PoliticaModControle();
        DocumentoControle d = new DocumentoControle();
        if (cmbTpMod.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(null,"Favor prencher os campos.");
        } else if (cmbTpMod.getSelectedItem().equals("Automática") && txtQtd.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Favor prencher a quantidade de palavras.");
        }else{
            try {
                String tipo = null;
                if (cmbTpMod.getSelectedItem().equals("Sob demanda")){
                    tipo = "M";
                } else {
                    tipo = "A";
                }
                Usuario usuario = SingletonUtil.getInstance().getUsuario();
                Documento doc = d.buscarDocumentoporId(TelaAnotacao.doc_id);
                pol.incluir(usuario, doc, tipo, txtQtd.getText());
                JOptionPane.showMessageDialog(null,"Política de modularização incluída com sucesso.");
                this.dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"Erro na inclusão da política de modularização. " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
   
}//GEN-LAST:event_formWindowActivated

    private void cmbTpModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTpModActionPerformed
       
    }//GEN-LAST:event_cmbTpModActionPerformed

    private void cmbTpModFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbTpModFocusLost
         if (cmbTpMod.getSelectedItem().equals("Sob demanda")){
            txtQtd.setText("");
            txtQtd.setEnabled(false);
        } else if (cmbTpMod.getSelectedItem().equals("Automática")){
            txtQtd.setEnabled(true);
            txtQtd.setText("");
        }
    }//GEN-LAST:event_cmbTpModFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaPoliticaMod().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cmbTpMod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtQtd;
    // End of variables declaration//GEN-END:variables
}
